### ISSUE TITLE
Нарушение авторских прав

### ISSUE THREAD

**Issue by Alexell** [paveL1boyko/MuskEmpireBot#10]
Почему ваш репозиторий не оформлен как форк? Я конечно вижу, что вы переписали весь мой бот, но это не отменяет того, что за основу был взят мой бот и что некоторые части кода, а также README у вас мои. Поэтому, для разрешения этотй ситуации, есть 3 варианта:

1. Вы удаляете репозиторий, делаете форк и накатываете поверх все ваши изменения.
2. Вы пишете свое README (в нем не должно быть ничего, что писал я), избавляетесь от всех моих фраз в логировании, а также от системы остановки по кол-ву ошибок и функционала инвестирования, т.к. вы используете для его работы мои данные.
3. Вы ничего не меняете в коде, но указываете в README, что некоторые части бота написаны мной или что за основу вы брали мой бот.

Выбирайте.

 **Оригинал репозитория:** https://github.com/Alexell/XEmpireBot

**Comment by Imaroubat** [comment]
Не душни

> Почему ваш репозиторий не оформлен как форк? Я конечно вижу, что вы переписали весь мой бот, но это не отменяет того, что за основу был взят мой бот и что некоторые части кода, а также README у вас мои. Поэтому, для разрешения этотй ситуации, есть 3 варианта:
> 
> 1. Вы удаляете репозиторий, делаете форк и накатываете поверх все ваши изменения.
> 2. Вы пишете свое README (в нем не должно быть ничего, что писал я), избавляетесь от всех моих фраз в логировании, а также от системы остановки по кол-ву ошибок и функционала инвестирования, т.к. вы используете для его работы мои данные.
> 3. Вы ничего не меняете в коде, но указываете в README, что некоторые части бота написаны мной или что за основу вы брали мой бот.
> 
> Выбирайте.
> 
> **Оригинал репозитория:** https://github.com/Alexell/XEmpireBot

Не душни

**Comment by Nord1cWarr1or** [comment]
согласен, тоже когда увидел этого бота, подумал что слишком похож на бота Алекса

**Comment by paveL1boyko** [comment]
> Почему ваш репозиторий не оформлен как форк? Я конечно вижу, что вы переписали весь мой бот, но это не отменяет того, что за основу был взят мой бот и что некоторые части кода, а также README у вас мои. Поэтому, для разрешения этотй ситуации, есть 3 варианта:
> 
> 1. Вы удаляете репозиторий, делаете форк и накатываете поверх все ваши изменения.
> 2. Вы пишете свое README (в нем не должно быть ничего, что писал я), избавляетесь от всех моих фраз в логировании, а также от системы остановки по кол-ву ошибок и функционала инвестирования, т.к. вы используете для его работы мои данные.
> 3. Вы ничего не меняете в коде, но указываете в README, что некоторые части бота написаны мной или что за основу вы брали мой бот.
> 
> Выбирайте.
> 
>  **Оригинал репозитория:** https://github.com/Alexell/XEmpireBot

Да твой код ужасный 🤦 решил переписать форкать было лень , по поводу ридми дале лень переписывать было , чутка поправил для юзеров а так бот в общем-то для себя писал , чет захотелось

**Comment by paveL1boyko** [comment]
> Почему ваш репозиторий не оформлен как форк? Я конечно вижу, что вы переписали весь мой бот, но это не отменяет того, что за основу был взят мой бот и что некоторые части кода, а также README у вас мои. Поэтому, для разрешения этотй ситуации, есть 3 варианта:
> 
> 1. Вы удаляете репозиторий, делаете форк и накатываете поверх все ваши изменения.
> 2. Вы пишете свое README (в нем не должно быть ничего, что писал я), избавляетесь от всех моих фраз в логировании, а также от системы остановки по кол-ву ошибок и функционала инвестирования, т.к. вы используете для его работы мои данные.
> 3. Вы ничего не меняете в коде, но указываете в README, что некоторые части бота написаны мной или что за основу вы брали мой бот.
> 
> Выбирайте.
> 
>  **Оригинал репозитория:** https://github.com/Alexell/XEmpireBot

А что жалко 😁😁😁 поделится фондами , мне лень писать сво сервак было , но нашел уже где взять

**Comment by paveL1boyko** [comment]
> согласен, тоже когда увидел этого бота, подумал что слишком похож на бота Алекса

Где ж он похож🤣🤣🤣

**Comment by paveL1boyko** [comment]
> Почему ваш репозиторий не оформлен как форк? Я конечно вижу, что вы переписали весь мой бот, но это не отменяет того, что за основу был взят мой бот и что некоторые части кода, а также README у вас мои. Поэтому, для разрешения этотй ситуации, есть 3 варианта:
> 
> 1. Вы удаляете репозиторий, делаете форк и накатываете поверх все ваши изменения.
> 2. Вы пишете свое README (в нем не должно быть ничего, что писал я), избавляетесь от всех моих фраз в логировании, а также от системы остановки по кол-ву ошибок и функционала инвестирования, т.к. вы используете для его работы мои данные.
> 3. Вы ничего не меняете в коде, но указываете в README, что некоторые части бота написаны мной или что за основу вы брали мой бот.
> 
> Выбирайте.
> 
>  **Оригинал репозитория:** https://github.com/Alexell/XEmpireBot

Если бы ты написал нормально код я бы форкну мн было бы проще и поддерживать и что то обрабатывать да и я б тогда не переписывал этот треш

**Comment by Nord1cWarr1or** [comment]
> Где ж он похож🤣🤣🤣

В readme

**Comment by paveL1boyko** [comment]
> > Где ж он похож🤣🤣🤣
> 
> В readme

Чтож окай поправлю так и быть 🤣🤣

**Comment by Alexell** [comment]
У меня обычный код, типичный для подобных проектов. Я считаю, что нет смысла заморачиваться ради временных проектов. Игра закончится и бот станет не нужен, так зачем тратить время на лишние заморочки? Задача какая? Чтобы работало. У меня все работает стабильно, бот без остановок неделю может работать, если в игре обновы не выходят, ломающие что-то. Таким образом цель достигнута. Тем не менее, я твой код видел и респект тебе за декораторы и в целом за качество, тут спору нет.

Что касается фондов, пришлось пойти на крайние меры. Если бы ты вовремя отреагировал на тикет и мы разрешили бы спор по теме, я бы дал тебе фонды может быть. А поскольку ты игнорил, для меня ты выглядел как "вор", поэтому я всячески мешал тебе "воровать" у меня фонды.

Что касается основной темы тикета, настоятельно рекомендую полностью переписать readme, не желаю там видеть ни единого предложения, написанного мной. Если претендуешь на то, что ты достаточно переписал код, то посмотри его внимательно, думаю ты найдешь места, которые в точности взяты у меня и не тронуты, с этим тоже поработай.

**Comment by paveL1boyko** [comment]
> У меня обычный код, типичный для подобных проектов. Я считаю, что нет смысла заморачиваться ради временных проектов. Игра закончится и бот станет не нужен, так зачем тратить время на лишние заморочки? Задача какая? Чтобы работало. У меня все работает стабильно, бот без остановок неделю может работать, если в игре обновы не выходят, ломающие что-то. Таким образом цель достигнута. Тем не менее, я твой код видел и респект тебе за декораторы и в целом за качество, тут спору нет.
> 
> Что касается фондов, пришлось пойти на крайние меры. Если бы ты вовремя отреагировал на тикет и мы разрешили бы спор по теме, я бы дал тебе фонды может быть. А поскольку ты игнорил, для меня ты выглядел как "вор", поэтому я всячески мешал тебе "воровать" у меня фонды.
> 
> Что касается основной темы тикета, настоятельно рекомендую полностью переписать readme, не желаю там видеть ни единого предложения, написанного мной. Если претендуешь на то, что ты достаточно переписал код, то посмотри его внимательно, думаю ты найдешь места, которые в точности взяты у меня и не тронуты, с этим тоже поработай.

если ты разаработчик то ты разработчик, а  кодер он так и рассуждает, а причем тут заморачиватся ты пишешь или нормальный код или кодишь вот и все
